config/routes.rb
Rails.application.routes.draw do

  root 'pages#accueil'
  get 'pages/contact'
  get 'pages/team'
  get 'pages/services'
  # connection / deconnection
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  # all resources
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { self.email = email.downcase }
  validates  :name, presence: true, length: {maximum: 50}
  validates :email, :presence => true,
  length: {maximum: 255},
  :format => { :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i},
  uniqueness: {case_sensitive: false}

  has_secure_password
  validates  :password, presence: true, length: {minimum: 6}, allow_nil: true

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    Bcrypt::password.new(remember_token).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def accueil
  end

  def contact
  end

  def team
  end

  def services

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user #je log l'utilisateur
      params[:session][:remember_me] == "1" ? remember(user) : forget(user) #sil la case est coché je me souviens de lui, sinon je l'oublie
      redirect_to user #je le redirige vers son profil
    else
      flash.now[:danger] = "Email ou mot de passe invalide !"
      render "new"
    end
  end

  def destroy
    log_out if logged_in? #je log out si l'utilisateur est log ( prevention multiple navigateur)
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit,:update,:destroy]
  before_action :logged_in_user, only: [:index,:edit,:update,:destroy]
  before_action :correct_user, only: [:edit,:update]
  before_action :admin_user, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      #Sauvegarde confirmé <- true
      log_in(@user)
      flash[:success] = "Bienvenue sur le clone de twitter"
      redirect_to @user
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profil mis à jour"
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "Utilisateur supprimé"
    redirect_to users_path
  end

  private

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Merci de vous connecter."
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper

  def full_title(page_title = "")
    base_title = "Ruby on Rails"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end



end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user?(user)
    user == current_user
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user_id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options= {size:80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class:"gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer>
  <p>&copy; michelDelpierre 2018-2019 tous droits réservés</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav">
        <li><%= link_to "Accueil", root_path%></li>
        <li><%= link_to "Services", pages_services_path%></li>
        <li><%= link_to "Team", pages_team_path%> </li>
        <li><%= link_to "Contact",pages_contact_path%> </li>
        <%if logged_in? %>
        <li><%= link_to "Utilisateurs",users_path%> </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Compte
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu" id="dropdown">
            <li><%= link_to "Profil", current_user %></li>
            <li><%= link_to "Paramètres", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Déconnexion", logout_path, method: :delete%></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Se connecter", login_path%></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=  full_title(yield(:title)) %> </title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/header' %>
  <section class="container">
    <% flash.each do |message_type,message|%>
    <div class="alert alert-<%= message_type%>">
      <%= message %>
    </div>
    <% end %>
    <%= yield %>
  </section>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/accueil.html.erb
<% provide(:title, "Accueil") %>
<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <p>
    &darr; Pour vous inscrire, cliquez simplement sur le bouton ci-dessous &darr;
  </p>
  <%= link_to "S'incrire maintenant", new_user_path, class:"btn btn-lg btn-primary"%>
</div>

app/views/pages/contact.html.erb
<% provide(:title, "contact") %>
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/services.html.erb
<% provide(:title, "services") %>

<h1>services</h1>

app/views/pages/team.html.erb
<% provide(:title, "team") %>

<h1>hello team</h1>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    Le formulaire contient <%= pluralize(@user.errors.count, "erreur") %>.
  </div>
  <ul class="list-form">
  <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user)%>
  | <%= link_to "supprimer", user, method: :delete, data: { confirm: "Supprimer l'utilisateur ?"}%>
  <% end %>
</li>

app/views/users/edit.html.erb
<%= provide(:title," Edition mon profil")%>
<h1 class="registrer-title">Mettre à jour votre profil</h1>
<div class="row">
  <%= form_for(@user) do |f| %>
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/error_messages'%>
    <%= f.label :name%>
    <%= f.text_field :name,class:'form-control'%>

    <%= f.label :email%>
    <%= f.email_field :email,class:'form-control'%>

    <%= f.label :password%>
    <%= f.password_field :password,class:'form-control'%>

    <%= f.label :password_confirmation, "Confirmation"%>
    <%= f.password_field :password_confirmation,class:'form-control'%>


    <%= f.submit "Sauvegarder les changementd", class:"btn btn-primary" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user%>
      <a href="http://gravatar.com/emails" target="_blank">changer l'image</a>
    </div>

    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Tous les utilisateurs') %>
<h1>Tous les utilisateurs</h1>

<%= will_paginate %>

<ul class="utilisateurs">
  <% @users.each do |user| %>
  <%= render user %>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<%= provide(:title," S'enregistrer")%>
<h1 class="registrer-title">S'enregistrer</h1>
<div class="row">
  <%= form_for(@user) do |f| %>
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/error_messages'%>
    <%= f.label :name%>
    <%= f.text_field :name,class:'form-control'%>

    <%= f.label :email%>
    <%= f.email_field :email,class:'form-control'%>

    <%= f.label :password%>
    <%= f.password_field :password,class:'form-control'%>

    <%= f.label :password_confirmation, "Confirmation"%>
    <%= f.password_field :password_confirmation,class:'form-control'%>

    <%= f.submit "Créer mon compte", class:"btn btn-primary" %>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name)%>

<div class="row">
  <aside class="col-md-4">
    <section class="info_utilisateur">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name%>
      </h1>
    </section>
  </aside>
</div>